### ISSUE TITLE
OPAs should expose poynting correction ability in Hardware

### ISSUE THREAD

**Issue by untzag** [wright-group/yaqc-cmds#115]

**Comment by wright-stuff** [comment]
There is currently a toggle box to turn poynting correction on and off, but it doesn't appear to do anything.

**Comment by ksunden** [comment]
It does, in fact do something, just not at the computer side. That was a bit of a hack that allows us to enable the manual knobs.  

Careful if you use this, if the knob is turned while disabled, and then it is enabled, it will go to the end of its range, which could cause lasers to be directed out of the table. The knobs are generally in their resting state, but they may be bumped with no effect until that box is checked
