### ISSUE TITLE
Hardware:  accept cases when motors take too long to get to their positions

### ISSUE THREAD

**Issue by ddkohler** [wright-group/yaqc-cmds#189]
Useful for when motor motion is impeded--should not result in a PyCMDS freeze.

**Comment by ksunden** [comment]
We need to figure out a heuristic to tell, as sometimes motors just simply take a while to move, so pure time may not be ideal. Could poll the encoder to make sure it's getting closer to the stop point

**Comment by kameyer226** [comment]
Could a is_moving() method (not trait) be employed?  An update_state could examine a previously stored get_position to determine if there was difference in values and set this above Boolean as such.   Then if is_moving() and busy() don't agree after a few turns it may be safe to throw an exception.  

Did not look to see if this was being done, and it requires of course an updating get_position.

**Comment by ksunden** [comment]
@kameyer226 I will note that this method predates `yaq`

In most cases, `busy` is exactly equivalent to `is_moving`, there is no other way to tell. In many ways this kind of thinking is _why_ we designed yaq as we did.

**Comment by ksunden** [comment]
I think this is out of scope for this repo at this stage... at least without real concrete proposal... I think such a feature would go to the individual daemon in question
