### ISSUE TITLE
importlib instead of imp

### ISSUE THREAD

**Issue by ksunden** [wright-group/yaqc-cmds#269]
imp is long deprecated

**Comment by ksunden** [comment]
though honestly, maybe we should use other things like entry points for some of the use cases...

**Comment by ksunden** [comment]
Basically applies to acquisition modules, as everywhere else is gobbled up by yaq... I think the modules should be entry points

**Comment by untzag** [comment]
I'm not convinced the modules should be /anything/...

**Comment by ksunden** [comment]
What is your alternative? we need at least scan and motor tune, and people like the tuning ones, find them easier to use than in the past... I know you have your hesitations, but I'm still pretty convinced the benefits outweigh the costs (though admittedly closer than I once was...)

Homing in the queue was also a requested feature, though absolutely willing to rethink the specifics of that....

**Comment by ksunden** [comment]
or is what you are saying to just directly import them by name, rather than either importlib or entry points...

**Comment by ksunden** [comment]
@untzag ??

**Comment by untzag** [comment]
I guess I'm just being grumpy. Sure, we should move to importlib. I'm hoping that we can get rid of the "module" construct eventually, but I don't have a concrete proposal at this time.

**Comment by untzag** [comment]
I really really don't want to build any more "plugin" systems unless we actually plan to document and support them---I'm very frustrated by our current "worst of both worlds" approach. I say :-1: to things like entry points until we actually have a come-to-jesus moment about the module abstraction.

**Comment by ksunden** [comment]
I guess my idea is to _use_ entry points _to_ solidify the interface... definitely some things I wish to change about it, not just simply tacking on entry points to what we have...
