### ISSUE TITLE
Spectrometers:  destination has limits imposed by current grating

### ISSUE THREAD

**Issue by ddkohler** [wright-group/yaqc-cmds#339]
e.g. on the visible grating, but destination grating is IR, the field does not let me write a destination outside the current grating bounds.  

workaround is to switch grating first and then move position, but note that this presents a problem if the grating limits do not overlap.

**Comment by ksunden** [comment]
This is not easy to fix... we read the limits from the daemon, and limits for other gratings are not visible without setting the turret.

note that it is not a problem if limits do not overlap, it will simply go to the nearest valid position.

Note also that I believe all spectrometers will overlap as they all provide 0 nm, in my experience.

**Comment by untzag** [comment]
I agree with @ksunden on this one. The client has no way to know what the limits will be until the turret is actually changed. We could build workarounds, of course, but they would just add fragility and complexity without significant gain in my opinion. Marking as WONTFIX.

@ddkohler feel free to re-open or comment if you disagree

**Comment by ddkohler** [comment]
I am wondering if the destination position form can just be unlimited in its inputs, while the daemon will just go to a limit if it is out of bounds?

**Comment by untzag** [comment]
that works, I guess... can you write out an example of what steps you would take and what you want the behavior to be?

**Comment by ksunden** [comment]
I don't like that plan, I think it is useful to have the feedback about the limits (even when they change, you know you changed the turret)
