### ISSUE TITLE
user access to shots

### ISSUE THREAD

**Issue by ddkohler** [wright-group/yaqc-cmds#340]
Currently no way to modify the number of shots in a measurement.  Proposed fix:

- [ ] make shots an argument in the acquisition form
- [ ] make daq a "hardware" with settable shots (for viewing channels when acquisitions are not running)

**Comment by ksunden** [comment]
please note that you _can_ set the number of shots using any python shell:

```
import yaqc
c = yaqc.Client(38999) #ni daemon port
c.set_nshots(1000)
```

That will hold


This is a duplicate issue of #299
