### ISSUE TITLE
Consistent hard crashes at end of acquisition from worker processing

### ISSUE THREAD

**Issue by ddkohler** [wright-group/yaqc-cmds#343]
Well known behavior, but I thought a formal issue was appropriate.  
Reproduce:  startup yaqc-cmds, run a few scans.  After 2-5 scans, yaqc-cmds will crash (no python errors).

Crash occurs for both motortune and scan acquisitions.

Not reproduced on Linux, or on fs table (to my knowledge).  

Likely related:  the acquisition that causes the crash creates a wt5 file that raises consistency flags, e.g.
```
>>> d = wt.open([path])
>>> wt.artists.quick2D(d)
Traceback (most recent call last):

  File "<ipython-input-1-2872b5fdde64>", line 6, in <module>
    d = wt.open(path)

  File "C:\Users\john\miniconda3\lib\site-packages\WrightTools\_open.py", line 56, in open
    f = h5py.File(filepath, "r")

  File "C:\Users\john\miniconda3\lib\site-packages\h5py\_hl\files.py", line 424, in __init__
    fid = make_fid(name, mode, userblock_size,

  File "C:\Users\john\miniconda3\lib\site-packages\h5py\_hl\files.py", line 190, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)

  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

  File "h5py\h5f.pyx", line 96, in h5py.h5f.open

OSError: Unable to open file (file is already open for write (may use <h5clear file> to clear file consistency flags))
```

**Comment by ddkohler** [comment]
Possibly related:  daq consistently freezes at the end of an acquisition.  Need to restart freerun to get updates again.

**Comment by ddkohler** [comment]
For scans, the line that causes the hard crash is the reading of data for the worker
https://github.com/wright-group/yaqc-cmds/blob/45b2ac0f67e5a139daac532fbce3ddc6d2bc5e56/yaqc_cmds/somatic/modules/scan.py#L117

**Comment by kameyer226** [comment]
https://opensource.com/article/17/4/grok-gil   Concurrency section 2/3 way down

Could this be a GIL issue?  May explain why it may work OK on Linux.

**Comment by ksunden** [comment]
I doubt this is the GIL... I don't understand why this is affecting the ps table but not the fs table...

**Comment by kameyer226** [comment]
Could either the HDD be failing or the driver be in error?  I don't recall if @untzag performed tests without writes.

**Comment by untzag** [comment]
I don't have a satisfying answer to describe the differences in behavior between different machines. I do believe that the crashes happen due to multiple threads colliding in some way. Problems like these are typically somewhat stochastic because they are so intricately dependent on timing. The ps system may be suffering most just because of the exact timing details - CPU speed, hard drive speed, hardware connected to yaqc-cmds etc...

I've almost never had a satisfying conclusion when tracing down these types of bugs.

**Comment by untzag** [comment]
That said, these bugs CAN be fixed by finding the system that's allowing the collision and putting thread-control measures in place. It's just hard to say exactly "this is why the program crashed in this instance".

**Comment by kameyer226** [comment]
Was/is it possible to test file locking like in 
https://stackoverflow.com/questions/57310333/can-we-disable-h5py-file-locking-for-python-file-like-object   .  Thought maybe this environment variable was toggled for some earlier reason.
