### ISSUE TITLE
sensor sleep time configurable?

### ISSUE THREAD

**Issue by ddkohler** [wright-group/yaqc-cmds#345]
We have a sleep command while waiting for the measurement:

https://github.com/wright-group/yaqc-cmds/blob/45b2ac0f67e5a139daac532fbce3ddc6d2bc5e56/yaqc_cmds/sensors/_sensors.py#L166

It sounds like putting a large wait time (i.e. 0.1 s) is beneficial for fake hardwares, while we want it shorter (<= 0.01 s) for actual hardware to minimize dead time.  Large wait times cause significant lag for few-shot acquisitions e.g.: https://gitlab.com/yaq/yaqd-ni/-/issues/2 

Given it seems a parameter that changes, should we make the wait time a parameter of config?

**Comment by untzag** [comment]
My vote is just to take the wait time out. We can fix the "fake sensors are too fast" problem by adding in waiting to our fake sensors, if necessary. I don't think yaqc-cmds should attempt to rate-limit fast sensors.

If the client is somehow brought to it's knees by too much sensor data that's another thing... but I don't think that's the problem that we were addressing by adding that wait.

**Comment by untzag** [comment]
closed by #349
