### ISSUE TITLE
yaqc-cmds bogs down cpu if delay motor is busy

### ISSUE THREAD

**Issue by ddkohler** [wright-group/yaqc-cmds#351]
fs table, d2 freezes busy, cpu maxes out.  CPU goes back to normal after yaqc-cmds closes (but daemon is still active and busy).

**Comment by ddkohler** [comment]
It must be the `while` loop that commits the cpu?
https://github.com/wright-group/yaqc-cmds/blob/231151940caa8479956389244b66eb0a62faacd3/yaqc_cmds/hardware/delays.py#L84-L90

Perhaps a sleep call within the loop fixes this...

**Comment by ksunden** [comment]
putting that sleep inside of the while loop may solve the problem, at least keep cpu usage down
