### ISSUE TITLE
yaqc-cmds fails to report current position on newport delays

### ISSUE THREAD

**Issue by ddkohler** [wright-group/yaqc-cmds#355]
seen on fs table.  Fairly often (perhaps 1 in 5 set_position calls), the newport delays will fail to report a change in current position upon moving.  An independent yaqc client can verify that the daemon position does not agree with the yaqc-cmds position reading.

Setting the position a second time to the same position (effectively calling get_position again) usually fixes this.

**Comment by untzag** [comment]
@ksunden what's the status on getting fixes to the newport daemons? We know the problem we know the fix... should I make time for this :thinking:

**Comment by ksunden** [comment]
I believe this is fixed, if not let me know
