### ISSUE TITLE
Method of freezing hardware 

### ISSUE THREAD

**Issue by kameyer226** [wright-group/yaqc-cmds#363]
Could not find method where a specific piece of hardware was "frozen", i.e., told not to move from its current position, during a scan of other hardware pieces.  Scan would always make the hardware move to the value in the control first.    Possible to "stop" a daemon associated with that hardware if freeze turned on, then jump over the check for that daemon during a scan?

**Comment by ksunden** [comment]
I'm inclined to say this is not necessary and is overcomplicated and error prone.

**Comment by ksunden** [comment]
Scans which do not scan a given hardware already do not set their position.... For motortunes, a system like this already exists (use "Static", i believe)

So its not clear to me what needs to be frozen... if you are scanning the hardware, it cannot be frozen.

**Comment by ksunden** [comment]
The autonomic system will make it move physical position, but only to compensate, and that can be turned off with a single checkbox

**Comment by kameyer226** [comment]
I believe the STATIC feature was the point I was missing, will see if that does what I hope to do

**Comment by untzag** [comment]
@kameyer226 are you thinking about tuning scans or experimental scans?

**Comment by kameyer226** [comment]
Experimental...what I wanted to do was hold one of the stages while allowing another user to move most of the rest of the stages for his experiments but keeping the fixed position of the held stage.

**Comment by untzag** [comment]
Hmm. Consider just removing that hardware from yaqc-cmds config?

**Comment by kameyer226** [comment]
Yes, after moving it to where it needs to be held it could stay there for a very long time

**Comment by kameyer226** [comment]
So that should work

**Comment by untzag** [comment]
Sounds good. Thanks for working through it with us :smile:
